### ISSUE TITLE
在centos无图形界面环境无法正常运行，需要在launch的时候添加额外的参数

### ISSUE THREAD

**Issue by rightgenius** [macacajs/macaca-puppeteer#2]
本身puppeteer在没有图形界面的环境中，运行就需要额外的调试。

参考：
https://github.com/GoogleChrome/puppeteer/issues/290

在阿里云的centos 7.3上，配置好puppeteer环境后，不能正常的执行macaca-puppeteer。看了下源码，修改macaca-puppeteer.js中启动的部分：

```Javascript
this.browser = yield puppeteer.launch({
      ignoreHTTPSErrors: true,
      headless: !this.args.show,
      args: ['--no-sandbox', '--disable-setuid-sandbox', '--headless']
    });
```
添加额外的args可以跑起来

**Comment by popomore** [comment]
是的，要加这两个参数

**Comment by rightgenius** [comment]
所以考虑默认加上参数吗？或者从this.args读取？
不然部署之前都要修改脚本，有点麻烦- -b

**Comment by popomore** [comment]
提个 PR？

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-puppeteer/pull/3

**Comment by sunqibuhuake** [comment]
有可能在headless: false 的时候运行成功吗？因为需要用到flash。
