### ISSUE TITLE
相对于puppeteer来说macaca-puppeteer有哪些优势呢？

### ISSUE THREAD

**Issue by CommanderXL** [macacajs/macaca-puppeteer#4]
首先感谢`macaca`团队做的努力，然后想了解下`macaca-puppeteer`基于`puppeteer`进行封装后有哪些优势呢？

**Comment by xudafeng** [comment]
@CommanderXL puppeteer是作为驱动被封装起来的。目的是提供统一的标准化能力，融合到Macaca社区。

更多介绍：https://macacajs.com/zh/introduction
